---
- name: Get the current caller identity information
  amazon.aws.aws_caller_info:
    region: us-gov-west-1
  register: caller_info

- name: Get the current caller identity information
  amazon.aws.aws_caller_info:
    region: us-gov-west-1
  register: caller_info

- name: Set deployment_environment variable
  ansible.builtin.set_fact:
    deployment_environment: "{{ lookup('ansible.builtin.vars', 'id_' + caller_info.account).deployment_environment }}"

- name: Set sample_environment variable
  ansible.builtin.set_fact:
    sample_environment: "{{ lookup('ansible.builtin.vars', 'id_' + caller_info.account).sample_environment }}"
